### ISSUE TITLE
Make twitter picture size fixed

### ISSUE THREAD

**Issue by ecagiral** [eguller/twitstreet#103]
Bigger twitter pictures corrupt page layout

**Comment by eguller** [comment]
@ecagiral Could you please send us an example account

**Comment by ecagiral** [comment]
AMCOUNTRYCNTWN
also search for carrieunderwood in order to see problem on "other results" panel

**Comment by eguller** [comment]
Fixed thanks.
Fix is not in live yet, it will be available in a few hours.
