### ISSUE TITLE
Performance improving

### ISSUE THREAD

**Issue by mpaltun** [eguller/twitstreet#126]
- Static files causes home page loading too late. Some of them is getting over 1 second load time and some files is requested more than once. I think there is no cache mechanism for static files.
- we have two nodes and one database so we dont have to run same background threads on same machine. They could be distributed.
- Tomcat consumes %100 of cpu.

We should focus especially the first one. Home page loading not bad but .js files loading too late from external resources.

**Comment by mushanga** [comment]
about #2

get twitter trends task is running on both nodes which is unnecessary. 

We should separate the scheduled task from servlet+mgr also.

**Comment by mushanga** [comment]
#2 does not mean "issue #2"...

**Comment by mpaltun** [comment]
- Tomcat issue fixed

In addition we should add indexes to tables where necessary.

**Comment by mpaltun** [comment]
Indexes added.
Loading duration is fine now.

Closed.
