### ISSUE TITLE
Show user history 

### ISSUE THREAD

**Issue by ecagiral** [eguller/twitstreet#147]
Show Buy/sell operation history in user details

**Comment by mushanga** [comment]
already existing olm zaten ne istiyon daha? now it shows only the current season's history. do you mean to show all history since the very first login?

**Comment by ecagiral** [comment]
I want to see other users. Like "Oh my god okay has a huge come back. I wonder his latest transactions". Or "Cagdas is a very genius guy I wonder his buy/sell operations". Maybe I can learn something from other users

**Comment by mushanga** [comment]
#89
