### ISSUE TITLE
Send twit to inactive users

### ISSUE THREAD

**Issue by eguller** [eguller/twitstreet#159]
Send twit to inactive users, who has an empty portfolio and cash = initial money
So maybe some of them will return to play twitstreet.
Send once a day only to one user. We do not want to mess left widget.

**Comment by mushanga** [comment]
Maybe sending an announcement before every season to each user that "new season is just about to start!" is enough... to all users... active/inactive doesn't matter... It's not disturbing to send this message every week I guess...
