### ISSUE TITLE
We are sending most popular tweets to new accounts

### ISSUE THREAD

**Issue by eguller** [eguller/twitstreet#183]
@MrBigShotCB1 Your follower count has increased 4329 in last 24 hours. You're the most popular person!

But @MrBigShotCB1 is newer than one week. 

@mushanga  if you are believe that it is right behaviour please close issue with a comment else fix.

**Comment by mushanga** [comment]
#160
we had already talked this issue and agreed on sending them anyway...

**Comment by eguller** [comment]
Ok
