### ISSUE TITLE
show "no results found" 

### ISSUE THREAD

**Issue by mushanga** [eguller/twitstreet#187]
there is nothing indicating that the search has no result. (for both users/stocks)

**Comment by eguller** [comment]
Actually there is for stock, but not just for user.

**Comment by mushanga** [comment]
Yeah I haven't checked Stocks and guessed it should have had the same problem as stocks/users search result screens are similar.. but it seems they're not :)

**Comment by mushanga** [comment]
after activity:dd5a483, no results found has been displayed by default, I'll fix that.. high priority
