### ISSUE TITLE
Search keywords in twitter and add them to suggested stocks

### ISSUE THREAD

**Issue by eguller** [eguller/twitstreet#188]
Listen search result of keywords like "welcome to twitter" , "joined to twitter" and add them trendy stocks.
This is what top users doing nowadays. We have to give a chance to give other users to find out these stocks at least from
suggested section.

**Comment by mushanga** [comment]
Enhance the "can be bought" constraint that it checks the time of the stock's very first tweet

do not allow the stocks just start tweeting to be bought. (7 days fine I guess)
