### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by hgo** [eguller/twitstreet#26]
not working

**Comment by eguller** [comment]
This was one of the frustrating problems. I have fixed the problem partially but it relogins you without asking credentials when you want to sign in again. It is is because you have already signed in twitter. If you want to change account you should aslo signout from twitter.

**Comment by hgo** [comment]
did you check the cookies?
21 Oca 2012 14:36 tarihinde "Engin Guller" <
reply@reply.github.com>
yazdı:

**Comment by eguller** [comment]
Yes I have checked cookies, I need to find a way to signout from twitter too. For now it does not seem possible with twitter4j library. I also saw people on the internet who has encountered similar problem.

**Comment by mpaltun** [comment]
I think we should reopen that again

**Comment by eguller** [comment]
Yes you are right, thanks it is not working properly

**Comment by mushanga** [comment]
noluyo la burada. ingilizce pratik mi yapiyosunuz :)

**Comment by mpaltun** [comment]
belki bi gun ecnebi bi developer el atar projeye onu bekliyoruz :D

**Comment by eguller** [comment]
Logout calismiyo iste amk ne olcak :) 
Ingilizce yazinca artistik oluyo ondan ole :)

**Comment by mushanga** [comment]
ehehehe alright then..

a song called "waiting for the stranger" is coming for this issue..

this issue is worse than we thought. Last night, I signed out from twitter, but it remembered me again and my friend couldn't get in.. 

requires further investigation...

**Comment by eguller** [comment]
This problem is still exist, user logs out but if it  goes to home page, logs in automatically again
